import { MoodMeta, WeatherMeta, DiaryEntry, MoodType, WeatherType } from '../types/diary';

export const MOODS: MoodMeta[] = [
  {
    type: 'ecstatic',
    label: '欣喜雀躍',
    emoji: '✨',
    color: '#E29578',
    bgLight: '#FFEEDB',
    bgDark: '#4A3425',
    textLight: '#8C481A',
    textDark: '#FFD7B5',
  },
  {
    type: 'happy',
    label: '開心愉快',
    emoji: '😊',
    color: '#83C5BE',
    bgLight: '#E8F6F4',
    bgDark: '#1E3F3B',
    textLight: '#165B54',
    textDark: '#A4E8DF',
  },
  {
    type: 'peaceful',
    label: '寧靜平和',
    emoji: '🌿',
    color: '#006D77',
    bgLight: '#E6F4F1',
    bgDark: '#18383B',
    textLight: '#004A51',
    textDark: '#8BE3DE',
  },
  {
    type: 'neutral',
    label: '平常平淡',
    emoji: '☕',
    color: '#6D6875',
    bgLight: '#F3F0F4',
    bgDark: '#2C2932',
    textLight: '#433E4C',
    textDark: '#D4CFDC',
  },
  {
    type: 'tired',
    label: '身心疲憊',
    emoji: '🥱',
    color: '#B5838D',
    bgLight: '#FAEDF0',
    bgDark: '#3D252B',
    textLight: '#7A3F4C',
    textDark: '#F4C2CC',
  },
  {
    type: 'sad',
    label: '低落沮喪',
    emoji: '🌧️',
    color: '#5E60CE',
    bgLight: '#EEF0FD',
    bgDark: '#26284F',
    textLight: '#393C98',
    textDark: '#C1C4FB',
  },
  {
    type: 'anxious',
    label: '焦慮不安',
    emoji: '⚡',
    color: '#E07A5F',
    bgLight: '#FDF0ED',
    bgDark: '#44231A',
    textLight: '#8A3C26',
    textDark: '#FFB8A5',
  },
];

export const WEATHERS: WeatherMeta[] = [
  { type: 'sunny', label: '晴朗', emoji: '☀️' },
  { type: 'cloudy', label: '多雲', emoji: '⛅' },
  { type: 'rainy', label: '陰雨', emoji: '🌧️' },
  { type: 'storm', label: '雷雨', emoji: '⛈️' },
  { type: 'snow', label: '雪', emoji: '❄️' },
  { type: 'foggy', label: '起霧', emoji: '🌫️' },
];

export const DEFAULT_TAGS = [
  '工作學習',
  '日常散策',
  '美食饗宴',
  '自我對話',
  '閱讀書香',
  '戶外運動',
  '家人朋友',
  '心懷感恩',
  '旅行足跡',
  '靈感隨想',
];

export const REFLECTION_PROMPTS = [
  '今天有哪一個微小的瞬間，讓你感到內心放鬆或微笑？',
  '今天完成了什麼雖然微小卻值得稱讚自己的事情？',
  '如果用三個詞形容今天的心情，你會選擇哪三個？',
  '今天最想感謝的一個人或一件事是什麼？',
  '今天碰到了什麼困擾，如果從明天的視角看它，會有不同感受嗎？',
  '今天喝了一杯好喝的咖啡或品嚐到美味的食物嗎？',
];

// Seed realistic sample entries
export const INITIAL_SAMPLE_ENTRIES: DiaryEntry[] = [
  {
    id: 'sample-entry-1',
    title: '下班路上的晚霞與一杯手沖咖啡',
    content: '今天下班經過河畔時，看見天空染上了漸層的紫金色與粉霞。駐足吹了十分鐘晚風，所有的疲勞彷彿都隨風散開。回到家沖了一壺耶加雪菲，柑橘的花果香在安靜的客廳飄散開來。\n\n給自己一個小約定：明天也要準時放下螢幕，多看看窗外的真實世界。',
    date: new Date(Date.now() - 0 * 86400000).toISOString().split('T')[0],
    time: '20:45',
    mood: 'peaceful',
    weather: 'sunny',
    tags: ['日常散策', '自我對話', '心懷感恩'],
    isFavorite: true,
    createdAt: new Date(Date.now() - 0 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 0 * 86400000).toISOString(),
  },
  {
    id: 'sample-entry-2',
    title: '完成了重要的專案提案，心頭大石放下',
    content: '準備了將近兩個禮拜的企劃案，今天在團隊會議上順利通過了！主辦方給予了很多正面反饋。雖然前幾天熬夜有些疲憊，但看到努力轉化為成果，內心充滿了踏實的喜悅。\n\n今晚要早點入睡，好好補眠修復體力。',
    date: new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0],
    time: '18:15',
    mood: 'ecstatic',
    weather: 'cloudy',
    tags: ['工作學習', '自我對話'],
    isFavorite: true,
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'sample-entry-3',
    title: '午後的雨聲與閱讀時光',
    content: '外面下起了綿綿細雨，窗戶玻璃被雨滴劃出一道道水痕。泡了一壺熱洋甘菊茶，重讀了赫曼·赫塞的《流浪者之歌》。\n\n「大多數人就像一片片落葉，在空中漂浮、翻滾，最後落在地上；但有些人卻像天上的星星，沿著固定的軌道前進。」每次讀到這段話，心境都會沉澱下來。',
    date: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
    time: '15:30',
    mood: 'peaceful',
    weather: 'rainy',
    tags: ['閱讀書香', '自我對話'],
    isFavorite: false,
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'sample-entry-4',
    title: '與久違的老友在公園散步漫聊',
    content: '下午和大學好友相約在公園走走，我們聊了各自近期的生活轉變、工作挑戰和未來的計畫。不知不覺就繞著湖心走了兩圈，買了路邊的手作肉桂捲，香氣非常療癒。\n\n能夠有隨時坦然談心、不需要客套的朋友，真的是人生很珍貴的禮物。',
    date: new Date(Date.now() - 4 * 86400000).toISOString().split('T')[0],
    time: '17:20',
    mood: 'happy',
    weather: 'sunny',
    tags: ['家人朋友', '日常散策', '心懷感恩'],
    isFavorite: true,
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'sample-entry-5',
    title: '有點手忙腳亂的一天，提醒自己慢下來',
    content: '今天突發事件有點多，早上的行程被延遲，下午又接到臨時改動的要求，情緒一度有些浮躁與焦慮。\n\n傍晚做了一次10分鐘的腹式呼吸練習，提醒自己：不能控制外界發生的所有事情，但能選擇如何回應。明天重新調整步調，一步一步來。',
    date: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
    time: '21:10',
    mood: 'anxious',
    weather: 'cloudy',
    tags: ['工作學習', '自我對話'],
    isFavorite: false,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  }
];
